service: amt-serverless-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  memorySize: 128
  timeout: 3
  httpApi:
    cors: true

functions:
  handler:
    handler: src/handler.handler
    description: Serverless API
    events:
      - httpApi: '*'
    vpc:
      securityGroupIds:
        - sg-02f5eda9078cfc936
      subnetIds:
        - subnet-06b64946d5bd245cc
        - subnet-07dd851f8623f0cdb
        - subnet-0061246b77354e87b

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    required:
      env:
        - DB_DIALECT
        - DB_HOST
        - DB_PORT
        - DB_USERNAME
        - DB_PASSWORD
        - DB_DATABASE